default_provider: openai_gpt5_low
fallback_chain:
  - openai_gpt4o_mini
  - local_gguf_small
temperature: 0.2
top_p: 1.0
max_tokens: 1200
embeddings_model: text-embedding-latest
budget:
  max_prompt_tokens: 12000
  max_completion_tokens: 6000
timeouts:
  request_ms: 20000
retries:
  attempts: 3
  base_delay_ms: 250
  max_delay_ms: 4000
