window_days: 7
defaults:
  rate_limit_qpm: 30
  timeout_ms: 15000
sources:
  - id: deepmind_blog
    kind: html
    url: https://deepmind.google/discover/blog/
    enabled: true
    metadata:
      source_name: DeepMind Blog
  - id: openai_blog
    kind: rss
    url: https://openai.com/blog/rss.xml
    rate_limit_qpm: 20
    enabled: true
    metadata:
      source_name: OpenAI Blog
  - id: anthropic
    kind: html
    url: https://www.anthropic.com/news
    enabled: false
  - id: huggingface
    kind: rss
    url: https://huggingface.co/blog/feed.xml
    enabled: true
  - id: gemini_product_news
    kind: html
    url: https://blog.google/products/gemini
    enabled: true
    metadata:
      source_name: Gemini Product News
  - id: xai_news
    kind: html
    url: https://x.ai/news
    enabled: true
    metadata:
      source_name: xAI News
      accept_language: en-US,en;q=0.9
      http_headers:
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        Sec-Ch-Ua: '"Chromium";v="125", "Not.A/Brand";v="24"'
        Sec-Ch-Ua-Mobile: '?0'
        Sec-Ch-Ua-Platform: '"macOS"'
        Sec-Fetch-Site: none
        Sec-Fetch-Mode: navigate
        Sec-Fetch-User: '?1'
        Upgrade-Insecure-Requests: '1'
        Referer: https://x.ai/
        Cache-Control: no-cache
        Pragma: no-cache
  - id: meta_ai_blog
    kind: html
    url: https://ai.meta.com/blog/
    enabled: true
    metadata:
      source_name: Meta AI Blog
      accept_language: en-US,en;q=0.9
  - id: microsoft_ai_news
    kind: rss
    url: https://news.microsoft.com/source/tag/ai/feed
    enabled: true
    metadata:
      source_name: Microsoft AI News
  - id: google_ai_news
    kind: rss
    url: https://news.google.com/rss/search?q=ai&hl=en-US&gl=US&ceid=US:en
    enabled: true
    metadata:
      source_name: Google AI News
  - id: paperswithcode
    kind: api
    url: https://paperswithcode.com/api/latest
    enabled: false
